#!/bin/bash
blk='\e[0;30m' red='\e[0;31m' grn='\e[0;32m' ylw='\e[0;33m'
blu='\e[0;34m' pur='\e[0;35m' cyn='\e[0;36m' wht='\e[0;37m'
clear
case "$1" in
	"")
clear
printf "${blu}Welcome To Alpine Termux For Android\n"
printf "${red}> ${wht}https://github.com/wahasa/Alpine"
printf "\n\n"
printf "${ylw}• Alpine 3.18"
printf "\n\n"
printf "${blu}Name    ${red}: ${grn}Alpine3.18\n"
printf "${blu}Version ${red}: ${grn}3.18.2\n"
printf "${blu}Status  ${red}: ${grn}Latest\n"
printf "${blu}Rootfs  ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${ylw}• Alpine 3.17"
printf "\n\n"
printf "${blu}Name    ${red}: ${grn}Alpine3.17\n"
printf "${blu}Version ${red}: ${grn}3.17.4\n"
printf "${blu}Status  ${red}: ${grn}Latest\n"
printf "${blu}Rootfs  ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${ylw}• Alpine 3.16"
printf "\n\n"
printf "${blu}Name    ${red}: ${grn}Alpine3.16\n"
printf "${blu}Version ${red}: ${grn}3.16.6\n"
printf "${blu}Status  ${red}: ${grn}Latest\n"
printf "${blu}Rootfs  ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${ylw}• Alpine (Development)"
printf "\n\n"
printf "${blu}Name    ${red}: ${grn}AlpineDev\n"
printf "${blu}Version ${red}: ${grn}Beta 3.18\n"
printf "${blu}Code    ${red}: ${grn}Edge\n"
printf "${blu}Rootfs  ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "AlpineDev")
wget https://raw.githubusercontent.com/wahasa/Alpine/main/Install/alpine.sh ; chmod +x alpine.sh ; bash alpine.sh
        ;;
        "Alpine3.18")
wget https://raw.githubusercontent.com/wahasa/Alpine/main/Install/alpine3.18.sh ; chmod +x alpine3.18.sh ; bash alpine3.18.sh
        ;;
        "Alpine3.17")
wget https://raw.githubusercontent.com/wahasa/Alpine/main/Install/alpine3.17.sh ; chmod +x alpine3.17.sh ; bash alpine3.17.sh
        ;;
        "Alpine3.16")
wget https://raw.githubusercontent.com/wahasa/Alpine/main/Install/alpine3.16.sh ; chmod +x alpine3.16.sh ; bash alpine3.16.sh
        ;;
        *)
	bash Install
        ;;
esac
